name: PrinceInfo
main: com.github.princeofmar5.PrinceInfo
version: 1.0
author: Princeofmar5
commands:
   pinfo:
      description: Gets info about something
      usage: /<command> [arg]
   pireload:
      description: Reloads from the config
      usage: /<command>
   plist:
      description: Lists the different args you can use
      usage: /<command>
permissions:
    princeinfo.reload:
        description: Gives access to the reload command
        default: op